### ISSUE TITLE
It's not working on webpack2

### ISSUE THREAD

**Issue by think2011** [carlsagan21/ejs-simple-loader#1]
webpack:2.3.3

Error:

```
ERROR in   Error: Child compilation failed:
  Module build failed: TypeError: Cannot read property 'config' of null
  
  
  - TypeError: Cannot read property 'config' of null
```

**Comment by sun-slaven** [comment]
+1

**Comment by sun-slaven** [comment]
your Purpose is so great!

**Comment by sun-slaven** [comment]
I found a solution:
`<%= require('./header.ejs')(templateParams) %> `
used in child tpl using ejs-loader

**Comment by carlsagan21** [comment]
Okay I fixed the problem. Please update to 0.1.1 instead.
`webpack2` changed ways to get options for loaders, so that was the point.
I showed who is the boss so it gonna be okay.
