### ISSUE TITLE
get variable from ejs-simple-loader

### ISSUE THREAD

**Issue by LuHua10** [carlsagan21/ejs-simple-loader#3]
Hi,
How can I get the variable from ejs-simple-loader in .ejs file

it's my config

`new HtmlWebpackPlugin({ 
    filename: './views/index.html', 
    template: 'ejs-simple-loader?title'+ 'toby' +'!./src/views/index.ejs', 
    inject: 'body', 
    hash: true, 
    chunks: ['index'], 
    alwaysWriteToDisk: true,
})`

Am i right?
`<title><%= title %></title> `

thanks for your help 👯‍♂️

**Comment by carlsagan21** [comment]
yup almost correct but careful not to miss '=' in a query string.
e.g. `template: 'ejs-simple-loader?title`**=**`'+ 'toby' +'!./src/views/index.ejs'`

`<title><%= title %></title>` is okay.

Thanks for your asking.

**Comment by LuHua10** [comment]
wow, you save my day!

Thanks for your helping 👍
